// source: AdvInfo.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

goog.provide('proto.ru.sovcombank.hackaton.proto.AdvInfo');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');
goog.require('proto.ru.sovcombank.hackaton.proto.AdvInfoData');
goog.require('proto.ru.sovcombank.hackaton.proto.AdvInfoFieldRef');

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.ru.sovcombank.hackaton.proto.AdvInfo = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.ru.sovcombank.hackaton.proto.AdvInfo.repeatedFields_, null);
};
goog.inherits(proto.ru.sovcombank.hackaton.proto.AdvInfo, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.ru.sovcombank.hackaton.proto.AdvInfo.displayName = 'proto.ru.sovcombank.hackaton.proto.AdvInfo';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.ru.sovcombank.hackaton.proto.AdvInfo.repeatedFields_ = [2];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.ru.sovcombank.hackaton.proto.AdvInfo.prototype.toObject = function(opt_includeInstance) {
  return proto.ru.sovcombank.hackaton.proto.AdvInfo.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.ru.sovcombank.hackaton.proto.AdvInfo} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ru.sovcombank.hackaton.proto.AdvInfo.toObject = function(includeInstance, msg) {
  var f, obj = {
    caption: jspb.Message.getFieldWithDefault(msg, 1, ""),
    fieldsList: jspb.Message.toObjectList(msg.getFieldsList(),
    proto.ru.sovcombank.hackaton.proto.AdvInfoFieldRef.toObject, includeInstance),
    data: (f = msg.getData()) && proto.ru.sovcombank.hackaton.proto.AdvInfoData.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.ru.sovcombank.hackaton.proto.AdvInfo}
 */
proto.ru.sovcombank.hackaton.proto.AdvInfo.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.ru.sovcombank.hackaton.proto.AdvInfo;
  return proto.ru.sovcombank.hackaton.proto.AdvInfo.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.ru.sovcombank.hackaton.proto.AdvInfo} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.ru.sovcombank.hackaton.proto.AdvInfo}
 */
proto.ru.sovcombank.hackaton.proto.AdvInfo.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setCaption(value);
      break;
    case 2:
      var value = new proto.ru.sovcombank.hackaton.proto.AdvInfoFieldRef;
      reader.readMessage(value,proto.ru.sovcombank.hackaton.proto.AdvInfoFieldRef.deserializeBinaryFromReader);
      msg.addFields(value);
      break;
    case 3:
      var value = new proto.ru.sovcombank.hackaton.proto.AdvInfoData;
      reader.readMessage(value,proto.ru.sovcombank.hackaton.proto.AdvInfoData.deserializeBinaryFromReader);
      msg.setData(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.ru.sovcombank.hackaton.proto.AdvInfo.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.ru.sovcombank.hackaton.proto.AdvInfo.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.ru.sovcombank.hackaton.proto.AdvInfo} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ru.sovcombank.hackaton.proto.AdvInfo.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getCaption();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getFieldsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      2,
      f,
      proto.ru.sovcombank.hackaton.proto.AdvInfoFieldRef.serializeBinaryToWriter
    );
  }
  f = message.getData();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      proto.ru.sovcombank.hackaton.proto.AdvInfoData.serializeBinaryToWriter
    );
  }
};


/**
 * optional string caption = 1;
 * @return {string}
 */
proto.ru.sovcombank.hackaton.proto.AdvInfo.prototype.getCaption = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.ru.sovcombank.hackaton.proto.AdvInfo} returns this
 */
proto.ru.sovcombank.hackaton.proto.AdvInfo.prototype.setCaption = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * repeated AdvInfoFieldRef fields = 2;
 * @return {!Array<!proto.ru.sovcombank.hackaton.proto.AdvInfoFieldRef>}
 */
proto.ru.sovcombank.hackaton.proto.AdvInfo.prototype.getFieldsList = function() {
  return /** @type{!Array<!proto.ru.sovcombank.hackaton.proto.AdvInfoFieldRef>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.ru.sovcombank.hackaton.proto.AdvInfoFieldRef, 2));
};


/**
 * @param {!Array<!proto.ru.sovcombank.hackaton.proto.AdvInfoFieldRef>} value
 * @return {!proto.ru.sovcombank.hackaton.proto.AdvInfo} returns this
*/
proto.ru.sovcombank.hackaton.proto.AdvInfo.prototype.setFieldsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 2, value);
};


/**
 * @param {!proto.ru.sovcombank.hackaton.proto.AdvInfoFieldRef=} opt_value
 * @param {number=} opt_index
 * @return {!proto.ru.sovcombank.hackaton.proto.AdvInfoFieldRef}
 */
proto.ru.sovcombank.hackaton.proto.AdvInfo.prototype.addFields = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 2, opt_value, proto.ru.sovcombank.hackaton.proto.AdvInfoFieldRef, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.ru.sovcombank.hackaton.proto.AdvInfo} returns this
 */
proto.ru.sovcombank.hackaton.proto.AdvInfo.prototype.clearFieldsList = function() {
  return this.setFieldsList([]);
};


/**
 * optional AdvInfoData data = 3;
 * @return {?proto.ru.sovcombank.hackaton.proto.AdvInfoData}
 */
proto.ru.sovcombank.hackaton.proto.AdvInfo.prototype.getData = function() {
  return /** @type{?proto.ru.sovcombank.hackaton.proto.AdvInfoData} */ (
    jspb.Message.getWrapperField(this, proto.ru.sovcombank.hackaton.proto.AdvInfoData, 3));
};


/**
 * @param {?proto.ru.sovcombank.hackaton.proto.AdvInfoData|undefined} value
 * @return {!proto.ru.sovcombank.hackaton.proto.AdvInfo} returns this
*/
proto.ru.sovcombank.hackaton.proto.AdvInfo.prototype.setData = function(value) {
  return jspb.Message.setWrapperField(this, 3, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.ru.sovcombank.hackaton.proto.AdvInfo} returns this
 */
proto.ru.sovcombank.hackaton.proto.AdvInfo.prototype.clearData = function() {
  return this.setData(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.ru.sovcombank.hackaton.proto.AdvInfo.prototype.hasData = function() {
  return jspb.Message.getField(this, 3) != null;
};


