// source: AdvInfoData.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

goog.provide('proto.ru.sovcombank.hackaton.proto.AdvInfoData');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');
goog.require('proto.ru.sovcombank.hackaton.proto.DataRow');

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.ru.sovcombank.hackaton.proto.AdvInfoData = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.ru.sovcombank.hackaton.proto.AdvInfoData.repeatedFields_, null);
};
goog.inherits(proto.ru.sovcombank.hackaton.proto.AdvInfoData, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.ru.sovcombank.hackaton.proto.AdvInfoData.displayName = 'proto.ru.sovcombank.hackaton.proto.AdvInfoData';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.ru.sovcombank.hackaton.proto.AdvInfoData.repeatedFields_ = [2];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.ru.sovcombank.hackaton.proto.AdvInfoData.prototype.toObject = function(opt_includeInstance) {
  return proto.ru.sovcombank.hackaton.proto.AdvInfoData.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.ru.sovcombank.hackaton.proto.AdvInfoData} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ru.sovcombank.hackaton.proto.AdvInfoData.toObject = function(includeInstance, msg) {
  var f, obj = {
    fullorincrement: jspb.Message.getBooleanFieldWithDefault(msg, 1, false),
    rowsList: jspb.Message.toObjectList(msg.getRowsList(),
    proto.ru.sovcombank.hackaton.proto.DataRow.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.ru.sovcombank.hackaton.proto.AdvInfoData}
 */
proto.ru.sovcombank.hackaton.proto.AdvInfoData.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.ru.sovcombank.hackaton.proto.AdvInfoData;
  return proto.ru.sovcombank.hackaton.proto.AdvInfoData.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.ru.sovcombank.hackaton.proto.AdvInfoData} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.ru.sovcombank.hackaton.proto.AdvInfoData}
 */
proto.ru.sovcombank.hackaton.proto.AdvInfoData.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setFullorincrement(value);
      break;
    case 2:
      var value = new proto.ru.sovcombank.hackaton.proto.DataRow;
      reader.readMessage(value,proto.ru.sovcombank.hackaton.proto.DataRow.deserializeBinaryFromReader);
      msg.addRows(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.ru.sovcombank.hackaton.proto.AdvInfoData.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.ru.sovcombank.hackaton.proto.AdvInfoData.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.ru.sovcombank.hackaton.proto.AdvInfoData} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ru.sovcombank.hackaton.proto.AdvInfoData.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getFullorincrement();
  if (f) {
    writer.writeBool(
      1,
      f
    );
  }
  f = message.getRowsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      2,
      f,
      proto.ru.sovcombank.hackaton.proto.DataRow.serializeBinaryToWriter
    );
  }
};


/**
 * optional bool fullOrIncrement = 1;
 * @return {boolean}
 */
proto.ru.sovcombank.hackaton.proto.AdvInfoData.prototype.getFullorincrement = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 1, false));
};


/**
 * @param {boolean} value
 * @return {!proto.ru.sovcombank.hackaton.proto.AdvInfoData} returns this
 */
proto.ru.sovcombank.hackaton.proto.AdvInfoData.prototype.setFullorincrement = function(value) {
  return jspb.Message.setProto3BooleanField(this, 1, value);
};


/**
 * repeated DataRow rows = 2;
 * @return {!Array<!proto.ru.sovcombank.hackaton.proto.DataRow>}
 */
proto.ru.sovcombank.hackaton.proto.AdvInfoData.prototype.getRowsList = function() {
  return /** @type{!Array<!proto.ru.sovcombank.hackaton.proto.DataRow>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.ru.sovcombank.hackaton.proto.DataRow, 2));
};


/**
 * @param {!Array<!proto.ru.sovcombank.hackaton.proto.DataRow>} value
 * @return {!proto.ru.sovcombank.hackaton.proto.AdvInfoData} returns this
*/
proto.ru.sovcombank.hackaton.proto.AdvInfoData.prototype.setRowsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 2, value);
};


/**
 * @param {!proto.ru.sovcombank.hackaton.proto.DataRow=} opt_value
 * @param {number=} opt_index
 * @return {!proto.ru.sovcombank.hackaton.proto.DataRow}
 */
proto.ru.sovcombank.hackaton.proto.AdvInfoData.prototype.addRows = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 2, opt_value, proto.ru.sovcombank.hackaton.proto.DataRow, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.ru.sovcombank.hackaton.proto.AdvInfoData} returns this
 */
proto.ru.sovcombank.hackaton.proto.AdvInfoData.prototype.clearRowsList = function() {
  return this.setRowsList([]);
};


