// source: DataRow.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

goog.provide('proto.ru.sovcombank.hackaton.proto.DataRow');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');
goog.require('proto.ru.sovcombank.hackaton.proto.ValueRef');

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.ru.sovcombank.hackaton.proto.DataRow = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.ru.sovcombank.hackaton.proto.DataRow.repeatedFields_, null);
};
goog.inherits(proto.ru.sovcombank.hackaton.proto.DataRow, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.ru.sovcombank.hackaton.proto.DataRow.displayName = 'proto.ru.sovcombank.hackaton.proto.DataRow';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.ru.sovcombank.hackaton.proto.DataRow.repeatedFields_ = [3];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.ru.sovcombank.hackaton.proto.DataRow.prototype.toObject = function(opt_includeInstance) {
  return proto.ru.sovcombank.hackaton.proto.DataRow.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.ru.sovcombank.hackaton.proto.DataRow} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ru.sovcombank.hackaton.proto.DataRow.toObject = function(includeInstance, msg) {
  var f, obj = {
    rowident: jspb.Message.getFieldWithDefault(msg, 1, ""),
    incrementdelete: jspb.Message.getBooleanFieldWithDefault(msg, 2, false),
    valuesList: jspb.Message.toObjectList(msg.getValuesList(),
    proto.ru.sovcombank.hackaton.proto.ValueRef.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.ru.sovcombank.hackaton.proto.DataRow}
 */
proto.ru.sovcombank.hackaton.proto.DataRow.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.ru.sovcombank.hackaton.proto.DataRow;
  return proto.ru.sovcombank.hackaton.proto.DataRow.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.ru.sovcombank.hackaton.proto.DataRow} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.ru.sovcombank.hackaton.proto.DataRow}
 */
proto.ru.sovcombank.hackaton.proto.DataRow.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setRowident(value);
      break;
    case 2:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setIncrementdelete(value);
      break;
    case 3:
      var value = new proto.ru.sovcombank.hackaton.proto.ValueRef;
      reader.readMessage(value,proto.ru.sovcombank.hackaton.proto.ValueRef.deserializeBinaryFromReader);
      msg.addValues(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.ru.sovcombank.hackaton.proto.DataRow.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.ru.sovcombank.hackaton.proto.DataRow.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.ru.sovcombank.hackaton.proto.DataRow} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ru.sovcombank.hackaton.proto.DataRow.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getRowident();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getIncrementdelete();
  if (f) {
    writer.writeBool(
      2,
      f
    );
  }
  f = message.getValuesList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      3,
      f,
      proto.ru.sovcombank.hackaton.proto.ValueRef.serializeBinaryToWriter
    );
  }
};


/**
 * optional string rowIdent = 1;
 * @return {string}
 */
proto.ru.sovcombank.hackaton.proto.DataRow.prototype.getRowident = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.ru.sovcombank.hackaton.proto.DataRow} returns this
 */
proto.ru.sovcombank.hackaton.proto.DataRow.prototype.setRowident = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional bool incrementDelete = 2;
 * @return {boolean}
 */
proto.ru.sovcombank.hackaton.proto.DataRow.prototype.getIncrementdelete = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 2, false));
};


/**
 * @param {boolean} value
 * @return {!proto.ru.sovcombank.hackaton.proto.DataRow} returns this
 */
proto.ru.sovcombank.hackaton.proto.DataRow.prototype.setIncrementdelete = function(value) {
  return jspb.Message.setProto3BooleanField(this, 2, value);
};


/**
 * repeated ValueRef values = 3;
 * @return {!Array<!proto.ru.sovcombank.hackaton.proto.ValueRef>}
 */
proto.ru.sovcombank.hackaton.proto.DataRow.prototype.getValuesList = function() {
  return /** @type{!Array<!proto.ru.sovcombank.hackaton.proto.ValueRef>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.ru.sovcombank.hackaton.proto.ValueRef, 3));
};


/**
 * @param {!Array<!proto.ru.sovcombank.hackaton.proto.ValueRef>} value
 * @return {!proto.ru.sovcombank.hackaton.proto.DataRow} returns this
*/
proto.ru.sovcombank.hackaton.proto.DataRow.prototype.setValuesList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 3, value);
};


/**
 * @param {!proto.ru.sovcombank.hackaton.proto.ValueRef=} opt_value
 * @param {number=} opt_index
 * @return {!proto.ru.sovcombank.hackaton.proto.ValueRef}
 */
proto.ru.sovcombank.hackaton.proto.DataRow.prototype.addValues = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 3, opt_value, proto.ru.sovcombank.hackaton.proto.ValueRef, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.ru.sovcombank.hackaton.proto.DataRow} returns this
 */
proto.ru.sovcombank.hackaton.proto.DataRow.prototype.clearValuesList = function() {
  return this.setValuesList([]);
};


