// source: OwnCommand.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

goog.provide('proto.ru.sovcombank.hackaton.proto.OwnCommand');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');
goog.require('proto.ru.sovcombank.hackaton.proto.Parameter');

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.ru.sovcombank.hackaton.proto.OwnCommand = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.ru.sovcombank.hackaton.proto.OwnCommand.repeatedFields_, null);
};
goog.inherits(proto.ru.sovcombank.hackaton.proto.OwnCommand, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.ru.sovcombank.hackaton.proto.OwnCommand.displayName = 'proto.ru.sovcombank.hackaton.proto.OwnCommand';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.ru.sovcombank.hackaton.proto.OwnCommand.repeatedFields_ = [4];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.ru.sovcombank.hackaton.proto.OwnCommand.prototype.toObject = function(opt_includeInstance) {
  return proto.ru.sovcombank.hackaton.proto.OwnCommand.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.ru.sovcombank.hackaton.proto.OwnCommand} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ru.sovcombank.hackaton.proto.OwnCommand.toObject = function(includeInstance, msg) {
  var f, obj = {
    alias: jspb.Message.getFieldWithDefault(msg, 1, ""),
    caption: jspb.Message.getFieldWithDefault(msg, 2, ""),
    description: jspb.Message.getFieldWithDefault(msg, 3, ""),
    parametersList: jspb.Message.toObjectList(msg.getParametersList(),
    proto.ru.sovcombank.hackaton.proto.Parameter.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.ru.sovcombank.hackaton.proto.OwnCommand}
 */
proto.ru.sovcombank.hackaton.proto.OwnCommand.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.ru.sovcombank.hackaton.proto.OwnCommand;
  return proto.ru.sovcombank.hackaton.proto.OwnCommand.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.ru.sovcombank.hackaton.proto.OwnCommand} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.ru.sovcombank.hackaton.proto.OwnCommand}
 */
proto.ru.sovcombank.hackaton.proto.OwnCommand.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setAlias(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setCaption(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setDescription(value);
      break;
    case 4:
      var value = new proto.ru.sovcombank.hackaton.proto.Parameter;
      reader.readMessage(value,proto.ru.sovcombank.hackaton.proto.Parameter.deserializeBinaryFromReader);
      msg.addParameters(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.ru.sovcombank.hackaton.proto.OwnCommand.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.ru.sovcombank.hackaton.proto.OwnCommand.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.ru.sovcombank.hackaton.proto.OwnCommand} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ru.sovcombank.hackaton.proto.OwnCommand.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getAlias();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 2));
  if (f != null) {
    writer.writeString(
      2,
      f
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 3));
  if (f != null) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getParametersList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      4,
      f,
      proto.ru.sovcombank.hackaton.proto.Parameter.serializeBinaryToWriter
    );
  }
};


/**
 * optional string alias = 1;
 * @return {string}
 */
proto.ru.sovcombank.hackaton.proto.OwnCommand.prototype.getAlias = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.ru.sovcombank.hackaton.proto.OwnCommand} returns this
 */
proto.ru.sovcombank.hackaton.proto.OwnCommand.prototype.setAlias = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string caption = 2;
 * @return {string}
 */
proto.ru.sovcombank.hackaton.proto.OwnCommand.prototype.getCaption = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.ru.sovcombank.hackaton.proto.OwnCommand} returns this
 */
proto.ru.sovcombank.hackaton.proto.OwnCommand.prototype.setCaption = function(value) {
  return jspb.Message.setField(this, 2, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.ru.sovcombank.hackaton.proto.OwnCommand} returns this
 */
proto.ru.sovcombank.hackaton.proto.OwnCommand.prototype.clearCaption = function() {
  return jspb.Message.setField(this, 2, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.ru.sovcombank.hackaton.proto.OwnCommand.prototype.hasCaption = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional string description = 3;
 * @return {string}
 */
proto.ru.sovcombank.hackaton.proto.OwnCommand.prototype.getDescription = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.ru.sovcombank.hackaton.proto.OwnCommand} returns this
 */
proto.ru.sovcombank.hackaton.proto.OwnCommand.prototype.setDescription = function(value) {
  return jspb.Message.setField(this, 3, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.ru.sovcombank.hackaton.proto.OwnCommand} returns this
 */
proto.ru.sovcombank.hackaton.proto.OwnCommand.prototype.clearDescription = function() {
  return jspb.Message.setField(this, 3, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.ru.sovcombank.hackaton.proto.OwnCommand.prototype.hasDescription = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * repeated Parameter parameters = 4;
 * @return {!Array<!proto.ru.sovcombank.hackaton.proto.Parameter>}
 */
proto.ru.sovcombank.hackaton.proto.OwnCommand.prototype.getParametersList = function() {
  return /** @type{!Array<!proto.ru.sovcombank.hackaton.proto.Parameter>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.ru.sovcombank.hackaton.proto.Parameter, 4));
};


/**
 * @param {!Array<!proto.ru.sovcombank.hackaton.proto.Parameter>} value
 * @return {!proto.ru.sovcombank.hackaton.proto.OwnCommand} returns this
*/
proto.ru.sovcombank.hackaton.proto.OwnCommand.prototype.setParametersList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 4, value);
};


/**
 * @param {!proto.ru.sovcombank.hackaton.proto.Parameter=} opt_value
 * @param {number=} opt_index
 * @return {!proto.ru.sovcombank.hackaton.proto.Parameter}
 */
proto.ru.sovcombank.hackaton.proto.OwnCommand.prototype.addParameters = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 4, opt_value, proto.ru.sovcombank.hackaton.proto.Parameter, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.ru.sovcombank.hackaton.proto.OwnCommand} returns this
 */
proto.ru.sovcombank.hackaton.proto.OwnCommand.prototype.clearParametersList = function() {
  return this.setParametersList([]);
};


