// source: Request.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

goog.provide('proto.ru.sovcombank.hackaton.proto.Request');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');
goog.require('proto.ru.sovcombank.hackaton.proto.OwnCommand');

goog.forwardDeclare('proto.ru.sovcombank.hackaton.proto.CommandType');
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.ru.sovcombank.hackaton.proto.Request = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.ru.sovcombank.hackaton.proto.Request.repeatedFields_, null);
};
goog.inherits(proto.ru.sovcombank.hackaton.proto.Request, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.ru.sovcombank.hackaton.proto.Request.displayName = 'proto.ru.sovcombank.hackaton.proto.Request';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.ru.sovcombank.hackaton.proto.Request.repeatedFields_ = [3];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.ru.sovcombank.hackaton.proto.Request.prototype.toObject = function(opt_includeInstance) {
  return proto.ru.sovcombank.hackaton.proto.Request.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.ru.sovcombank.hackaton.proto.Request} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ru.sovcombank.hackaton.proto.Request.toObject = function(includeInstance, msg) {
  var f, obj = {
    command: jspb.Message.getFieldWithDefault(msg, 1, 0),
    commandforexec: (f = msg.getCommandforexec()) && proto.ru.sovcombank.hackaton.proto.OwnCommand.toObject(includeInstance, f),
    supportedcommandsList: jspb.Message.toObjectList(msg.getSupportedcommandsList(),
    proto.ru.sovcombank.hackaton.proto.OwnCommand.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.ru.sovcombank.hackaton.proto.Request}
 */
proto.ru.sovcombank.hackaton.proto.Request.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.ru.sovcombank.hackaton.proto.Request;
  return proto.ru.sovcombank.hackaton.proto.Request.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.ru.sovcombank.hackaton.proto.Request} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.ru.sovcombank.hackaton.proto.Request}
 */
proto.ru.sovcombank.hackaton.proto.Request.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!proto.ru.sovcombank.hackaton.proto.CommandType} */ (reader.readEnum());
      msg.setCommand(value);
      break;
    case 2:
      var value = new proto.ru.sovcombank.hackaton.proto.OwnCommand;
      reader.readMessage(value,proto.ru.sovcombank.hackaton.proto.OwnCommand.deserializeBinaryFromReader);
      msg.setCommandforexec(value);
      break;
    case 3:
      var value = new proto.ru.sovcombank.hackaton.proto.OwnCommand;
      reader.readMessage(value,proto.ru.sovcombank.hackaton.proto.OwnCommand.deserializeBinaryFromReader);
      msg.addSupportedcommands(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.ru.sovcombank.hackaton.proto.Request.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.ru.sovcombank.hackaton.proto.Request.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.ru.sovcombank.hackaton.proto.Request} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ru.sovcombank.hackaton.proto.Request.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getCommand();
  if (f !== 0.0) {
    writer.writeEnum(
      1,
      f
    );
  }
  f = message.getCommandforexec();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.ru.sovcombank.hackaton.proto.OwnCommand.serializeBinaryToWriter
    );
  }
  f = message.getSupportedcommandsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      3,
      f,
      proto.ru.sovcombank.hackaton.proto.OwnCommand.serializeBinaryToWriter
    );
  }
};


/**
 * optional CommandType command = 1;
 * @return {!proto.ru.sovcombank.hackaton.proto.CommandType}
 */
proto.ru.sovcombank.hackaton.proto.Request.prototype.getCommand = function() {
  return /** @type {!proto.ru.sovcombank.hackaton.proto.CommandType} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {!proto.ru.sovcombank.hackaton.proto.CommandType} value
 * @return {!proto.ru.sovcombank.hackaton.proto.Request} returns this
 */
proto.ru.sovcombank.hackaton.proto.Request.prototype.setCommand = function(value) {
  return jspb.Message.setProto3EnumField(this, 1, value);
};


/**
 * optional OwnCommand commandForExec = 2;
 * @return {?proto.ru.sovcombank.hackaton.proto.OwnCommand}
 */
proto.ru.sovcombank.hackaton.proto.Request.prototype.getCommandforexec = function() {
  return /** @type{?proto.ru.sovcombank.hackaton.proto.OwnCommand} */ (
    jspb.Message.getWrapperField(this, proto.ru.sovcombank.hackaton.proto.OwnCommand, 2));
};


/**
 * @param {?proto.ru.sovcombank.hackaton.proto.OwnCommand|undefined} value
 * @return {!proto.ru.sovcombank.hackaton.proto.Request} returns this
*/
proto.ru.sovcombank.hackaton.proto.Request.prototype.setCommandforexec = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.ru.sovcombank.hackaton.proto.Request} returns this
 */
proto.ru.sovcombank.hackaton.proto.Request.prototype.clearCommandforexec = function() {
  return this.setCommandforexec(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.ru.sovcombank.hackaton.proto.Request.prototype.hasCommandforexec = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * repeated OwnCommand supportedCommands = 3;
 * @return {!Array<!proto.ru.sovcombank.hackaton.proto.OwnCommand>}
 */
proto.ru.sovcombank.hackaton.proto.Request.prototype.getSupportedcommandsList = function() {
  return /** @type{!Array<!proto.ru.sovcombank.hackaton.proto.OwnCommand>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.ru.sovcombank.hackaton.proto.OwnCommand, 3));
};


/**
 * @param {!Array<!proto.ru.sovcombank.hackaton.proto.OwnCommand>} value
 * @return {!proto.ru.sovcombank.hackaton.proto.Request} returns this
*/
proto.ru.sovcombank.hackaton.proto.Request.prototype.setSupportedcommandsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 3, value);
};


/**
 * @param {!proto.ru.sovcombank.hackaton.proto.OwnCommand=} opt_value
 * @param {number=} opt_index
 * @return {!proto.ru.sovcombank.hackaton.proto.OwnCommand}
 */
proto.ru.sovcombank.hackaton.proto.Request.prototype.addSupportedcommands = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 3, opt_value, proto.ru.sovcombank.hackaton.proto.OwnCommand, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.ru.sovcombank.hackaton.proto.Request} returns this
 */
proto.ru.sovcombank.hackaton.proto.Request.prototype.clearSupportedcommandsList = function() {
  return this.setSupportedcommandsList([]);
};


