// source: Response.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

goog.provide('proto.ru.sovcombank.hackaton.proto.Response');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');
goog.require('proto.ru.sovcombank.hackaton.proto.Status');

goog.forwardDeclare('proto.ru.sovcombank.hackaton.proto.AnswerType');
goog.forwardDeclare('proto.ru.sovcombank.hackaton.proto.CommandType');
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.ru.sovcombank.hackaton.proto.Response = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.ru.sovcombank.hackaton.proto.Response, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.ru.sovcombank.hackaton.proto.Response.displayName = 'proto.ru.sovcombank.hackaton.proto.Response';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.ru.sovcombank.hackaton.proto.Response.prototype.toObject = function(opt_includeInstance) {
  return proto.ru.sovcombank.hackaton.proto.Response.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.ru.sovcombank.hackaton.proto.Response} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ru.sovcombank.hackaton.proto.Response.toObject = function(includeInstance, msg) {
  var f, obj = {
    command: jspb.Message.getFieldWithDefault(msg, 1, 0),
    answertype: jspb.Message.getFieldWithDefault(msg, 2, 0),
    errortext: jspb.Message.getFieldWithDefault(msg, 3, ""),
    status: (f = msg.getStatus()) && proto.ru.sovcombank.hackaton.proto.Status.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.ru.sovcombank.hackaton.proto.Response}
 */
proto.ru.sovcombank.hackaton.proto.Response.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.ru.sovcombank.hackaton.proto.Response;
  return proto.ru.sovcombank.hackaton.proto.Response.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.ru.sovcombank.hackaton.proto.Response} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.ru.sovcombank.hackaton.proto.Response}
 */
proto.ru.sovcombank.hackaton.proto.Response.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!proto.ru.sovcombank.hackaton.proto.CommandType} */ (reader.readEnum());
      msg.setCommand(value);
      break;
    case 2:
      var value = /** @type {!proto.ru.sovcombank.hackaton.proto.AnswerType} */ (reader.readEnum());
      msg.setAnswertype(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setErrortext(value);
      break;
    case 4:
      var value = new proto.ru.sovcombank.hackaton.proto.Status;
      reader.readMessage(value,proto.ru.sovcombank.hackaton.proto.Status.deserializeBinaryFromReader);
      msg.setStatus(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.ru.sovcombank.hackaton.proto.Response.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.ru.sovcombank.hackaton.proto.Response.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.ru.sovcombank.hackaton.proto.Response} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ru.sovcombank.hackaton.proto.Response.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getCommand();
  if (f !== 0.0) {
    writer.writeEnum(
      1,
      f
    );
  }
  f = message.getAnswertype();
  if (f !== 0.0) {
    writer.writeEnum(
      2,
      f
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 3));
  if (f != null) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getStatus();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      proto.ru.sovcombank.hackaton.proto.Status.serializeBinaryToWriter
    );
  }
};


/**
 * optional CommandType command = 1;
 * @return {!proto.ru.sovcombank.hackaton.proto.CommandType}
 */
proto.ru.sovcombank.hackaton.proto.Response.prototype.getCommand = function() {
  return /** @type {!proto.ru.sovcombank.hackaton.proto.CommandType} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {!proto.ru.sovcombank.hackaton.proto.CommandType} value
 * @return {!proto.ru.sovcombank.hackaton.proto.Response} returns this
 */
proto.ru.sovcombank.hackaton.proto.Response.prototype.setCommand = function(value) {
  return jspb.Message.setProto3EnumField(this, 1, value);
};


/**
 * optional AnswerType answerType = 2;
 * @return {!proto.ru.sovcombank.hackaton.proto.AnswerType}
 */
proto.ru.sovcombank.hackaton.proto.Response.prototype.getAnswertype = function() {
  return /** @type {!proto.ru.sovcombank.hackaton.proto.AnswerType} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {!proto.ru.sovcombank.hackaton.proto.AnswerType} value
 * @return {!proto.ru.sovcombank.hackaton.proto.Response} returns this
 */
proto.ru.sovcombank.hackaton.proto.Response.prototype.setAnswertype = function(value) {
  return jspb.Message.setProto3EnumField(this, 2, value);
};


/**
 * optional string errorText = 3;
 * @return {string}
 */
proto.ru.sovcombank.hackaton.proto.Response.prototype.getErrortext = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.ru.sovcombank.hackaton.proto.Response} returns this
 */
proto.ru.sovcombank.hackaton.proto.Response.prototype.setErrortext = function(value) {
  return jspb.Message.setField(this, 3, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.ru.sovcombank.hackaton.proto.Response} returns this
 */
proto.ru.sovcombank.hackaton.proto.Response.prototype.clearErrortext = function() {
  return jspb.Message.setField(this, 3, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.ru.sovcombank.hackaton.proto.Response.prototype.hasErrortext = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional Status status = 4;
 * @return {?proto.ru.sovcombank.hackaton.proto.Status}
 */
proto.ru.sovcombank.hackaton.proto.Response.prototype.getStatus = function() {
  return /** @type{?proto.ru.sovcombank.hackaton.proto.Status} */ (
    jspb.Message.getWrapperField(this, proto.ru.sovcombank.hackaton.proto.Status, 4));
};


/**
 * @param {?proto.ru.sovcombank.hackaton.proto.Status|undefined} value
 * @return {!proto.ru.sovcombank.hackaton.proto.Response} returns this
*/
proto.ru.sovcombank.hackaton.proto.Response.prototype.setStatus = function(value) {
  return jspb.Message.setWrapperField(this, 4, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.ru.sovcombank.hackaton.proto.Response} returns this
 */
proto.ru.sovcombank.hackaton.proto.Response.prototype.clearStatus = function() {
  return this.setStatus(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.ru.sovcombank.hackaton.proto.Response.prototype.hasStatus = function() {
  return jspb.Message.getField(this, 4) != null;
};


