// source: Status.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

goog.provide('proto.ru.sovcombank.hackaton.proto.Status');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');
goog.require('proto.ru.sovcombank.hackaton.proto.AdvInfo');

goog.forwardDeclare('proto.ru.sovcombank.hackaton.proto.StatusType');
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.ru.sovcombank.hackaton.proto.Status = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.ru.sovcombank.hackaton.proto.Status, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.ru.sovcombank.hackaton.proto.Status.displayName = 'proto.ru.sovcombank.hackaton.proto.Status';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.ru.sovcombank.hackaton.proto.Status.prototype.toObject = function(opt_includeInstance) {
  return proto.ru.sovcombank.hackaton.proto.Status.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.ru.sovcombank.hackaton.proto.Status} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ru.sovcombank.hackaton.proto.Status.toObject = function(includeInstance, msg) {
  var f, obj = {
    type: jspb.Message.getFieldWithDefault(msg, 1, 0),
    details: jspb.Message.getFieldWithDefault(msg, 2, ""),
    nexttime: jspb.Message.getFieldWithDefault(msg, 3, 0),
    advstatus: (f = msg.getAdvstatus()) && proto.ru.sovcombank.hackaton.proto.AdvInfo.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.ru.sovcombank.hackaton.proto.Status}
 */
proto.ru.sovcombank.hackaton.proto.Status.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.ru.sovcombank.hackaton.proto.Status;
  return proto.ru.sovcombank.hackaton.proto.Status.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.ru.sovcombank.hackaton.proto.Status} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.ru.sovcombank.hackaton.proto.Status}
 */
proto.ru.sovcombank.hackaton.proto.Status.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!proto.ru.sovcombank.hackaton.proto.StatusType} */ (reader.readEnum());
      msg.setType(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setDetails(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setNexttime(value);
      break;
    case 4:
      var value = new proto.ru.sovcombank.hackaton.proto.AdvInfo;
      reader.readMessage(value,proto.ru.sovcombank.hackaton.proto.AdvInfo.deserializeBinaryFromReader);
      msg.setAdvstatus(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.ru.sovcombank.hackaton.proto.Status.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.ru.sovcombank.hackaton.proto.Status.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.ru.sovcombank.hackaton.proto.Status} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ru.sovcombank.hackaton.proto.Status.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getType();
  if (f !== 0.0) {
    writer.writeEnum(
      1,
      f
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 2));
  if (f != null) {
    writer.writeString(
      2,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 3));
  if (f != null) {
    writer.writeInt64(
      3,
      f
    );
  }
  f = message.getAdvstatus();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      proto.ru.sovcombank.hackaton.proto.AdvInfo.serializeBinaryToWriter
    );
  }
};


/**
 * optional StatusType type = 1;
 * @return {!proto.ru.sovcombank.hackaton.proto.StatusType}
 */
proto.ru.sovcombank.hackaton.proto.Status.prototype.getType = function() {
  return /** @type {!proto.ru.sovcombank.hackaton.proto.StatusType} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {!proto.ru.sovcombank.hackaton.proto.StatusType} value
 * @return {!proto.ru.sovcombank.hackaton.proto.Status} returns this
 */
proto.ru.sovcombank.hackaton.proto.Status.prototype.setType = function(value) {
  return jspb.Message.setProto3EnumField(this, 1, value);
};


/**
 * optional string details = 2;
 * @return {string}
 */
proto.ru.sovcombank.hackaton.proto.Status.prototype.getDetails = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.ru.sovcombank.hackaton.proto.Status} returns this
 */
proto.ru.sovcombank.hackaton.proto.Status.prototype.setDetails = function(value) {
  return jspb.Message.setField(this, 2, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.ru.sovcombank.hackaton.proto.Status} returns this
 */
proto.ru.sovcombank.hackaton.proto.Status.prototype.clearDetails = function() {
  return jspb.Message.setField(this, 2, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.ru.sovcombank.hackaton.proto.Status.prototype.hasDetails = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional int64 nextTime = 3;
 * @return {number}
 */
proto.ru.sovcombank.hackaton.proto.Status.prototype.getNexttime = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {number} value
 * @return {!proto.ru.sovcombank.hackaton.proto.Status} returns this
 */
proto.ru.sovcombank.hackaton.proto.Status.prototype.setNexttime = function(value) {
  return jspb.Message.setField(this, 3, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.ru.sovcombank.hackaton.proto.Status} returns this
 */
proto.ru.sovcombank.hackaton.proto.Status.prototype.clearNexttime = function() {
  return jspb.Message.setField(this, 3, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.ru.sovcombank.hackaton.proto.Status.prototype.hasNexttime = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional AdvInfo advStatus = 4;
 * @return {?proto.ru.sovcombank.hackaton.proto.AdvInfo}
 */
proto.ru.sovcombank.hackaton.proto.Status.prototype.getAdvstatus = function() {
  return /** @type{?proto.ru.sovcombank.hackaton.proto.AdvInfo} */ (
    jspb.Message.getWrapperField(this, proto.ru.sovcombank.hackaton.proto.AdvInfo, 4));
};


/**
 * @param {?proto.ru.sovcombank.hackaton.proto.AdvInfo|undefined} value
 * @return {!proto.ru.sovcombank.hackaton.proto.Status} returns this
*/
proto.ru.sovcombank.hackaton.proto.Status.prototype.setAdvstatus = function(value) {
  return jspb.Message.setWrapperField(this, 4, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.ru.sovcombank.hackaton.proto.Status} returns this
 */
proto.ru.sovcombank.hackaton.proto.Status.prototype.clearAdvstatus = function() {
  return this.setAdvstatus(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.ru.sovcombank.hackaton.proto.Status.prototype.hasAdvstatus = function() {
  return jspb.Message.getField(this, 4) != null;
};


